---
title: "Project 2 self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing

### Editing


## Introduction
### Literature research

### Writing

### Editing


## Methods
### Writing

- wrote the first half of the methods portion explaining data collection, TreeSAPP, and iTOL

### Editing

- edited in general
- edited the codes portion of the methods 

## Results
### Analysis 

### Figures

- made multiple figures but many were scrapped as I worked together with another member to improve on each others codes
- combined the figures together at the very end
- formated the document and created the final supplementary.rmd file for submission

### Writing

- wrote figure captions and also small portion on the phylogenetic trees

### Editing

- helped edit 

## Discussion
### Literature research

### Writing

### Editing

