---
title: "Project self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing

### Editing
- helped edit 

## Introduction
### Literature research

### Writing

### Editing


## Methods
### Writing

### Editing
- edited/cut out extraneous information

## Results
### Anaysis 

### Figures
- made most of the figures for OTU 
- worked together with another member on ASV figures
- troubleshot the looping code for p-values because it didn't work for OTUs for some reason
- format figures into for the draft
- make a Rmd with all the code for the final draft

### Writing
- helped write  

### Editing
- helped edit  

## Discussion
### Literature research

### Writing
- helped write section on OTU/ASVs 

### Editing

